- name: "Installing"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: "Add repositories"
      block:
        - name: "Add InfluxDB repository"
          yum_repository:
            name: influxdb
            description: InfluxDB Repository
            baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
            gpgcheck: no
            proxy: "{{ proxy | default('_none_') }}"

        - name: "Add CentOS repository"
          yum_repository:
            name: centos-updates
            description: "CentOS-$releasever - Updates"
            mirrorlist: http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
            gpgcheck: no
            proxy: "{{ proxy | default('_none_') }}"
          when: add_system_repo == true

    - name: "Install the latest version of InfluxDB"
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - curl
          - influxdb
      notify:
        - restart influxd

    - name: "Creates directory {{ influxdb.path | default('/var/lib/influxdb') }} for InfluxDB"
      file:
        path: "{{ influxdb.path | default('/var/lib/influxdb') }}"
        state: directory
        mode: 0755
        group: influxdb
        owner: influxdb
      notify:
        - restart influxd

    - name: "Create InfluxDB config"
      template:
        src: "{{ item.name }}.j2"
        dest: "/{{ item.name }}"
        mode: "{{ item.mode }}"
        owner: "root"
        group: "root"
      loop:
        - { name: "etc/influxdb/influxdb.conf", mode: "0644" }
      notify:
        - restart influxd
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: Stop InfluxDB
      systemd:
        name: influxdb
        state: stopped
        enabled: no

    - name: "Uninstall InfluxDB"
      yum:
        name: influxdb
        autoremove: yes
        state: absent

    - name: "Purge project files"
      block:
        - name: "Collecting project files"
          stat:
            path: "{{item}}"
          register: folder_stats
          with_items:
            - "/etc/influxdb"
            - "{{ influxdb.path | default('/var/lib/influxdb') }}"
            - "/etc/yum.repos.d/influxdb.repo"
        - name: "Delete project files"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == false
          with_items:
            - "{{folder_stats.results}}"
        - name: "Delete project folders"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == true
          with_items:
            - "{{folder_stats.results}}"
      ignore_errors: yes
  when: state == "absent"
