- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for InfluxDB repository"
          apt_key:
            url: "https://repos.influxdata.com/influxdb.key"
            state: present

        - name: "Add InfluxDB repository"
          apt_repository:
            repo: deb https://repos.influxdata.com/debian {{ ansible_facts['lsb']['codename'] }} stable
            state: present
            filename: influxdb

    - name: "Install the latest version of InfluxDB"
      apt:
        pkg:
          - curl
          - influxdb
        update_cache: yes
      notify:
        - restart influxd

    - name: "Creates directory {{ influxdb.path | default('/var/lib/influxdb') }} for InfluxDB"
      file:
        path: "{{ influxdb.path | default('/var/lib/influxdb') }}"
        state: directory
        mode: 0755
        group: influxdb
        owner: influxdb
      notify:
        - restart influxd

    - name: "Create InfluxDB config"
      template:
        src: "{{ item.name }}.j2"
        dest: "/{{ item.name }}"
        mode: "{{ item.mode }}"
        owner: "root"
        group: "root"
      loop:
        - { name: "etc/influxdb/influxdb.conf", mode: "0644" }
      notify:
        - restart influxd
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: Stop InfluxDB
      systemd:
        name: influxdb
        state: stopped
        enabled: no

    - name: "Uninstall InfluxDB"
      apt:
        name: influxdb
        state: absent

    - name: "Purge project files"
      block:
        - name: "Collecting project files"
          stat:
            path: "{{item}}"
          register: folder_stats
          with_items:
            - "/etc/influxdb"
            - "{{ influxdb.path | default('/var/lib/influxdb') }}"
            - "/etc/yum.repos.d/influxdb.repo"
        - name: "Delete project files"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == false
          with_items:
            - "{{folder_stats.results}}"
        - name: "Delete project folders"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == true
          with_items:
            - "{{folder_stats.results}}"
      ignore_errors: yes
  when: state == "absent"
