- name: "Install Statistics Storage for CentOS"
  include: centos.yml
  when:
    - ansible_facts['distribution'] | lower == "centos"

- name: "Install Statistics Storage for Debian"
  include: debian.yml
  when:
    - ansible_facts['distribution'] | lower == "debian"
    - ansible_facts['distribution_major_version'] | int >= 9
