- name: "Install Statistics Storage for CentOS"
  include: centos.yml
  when:
    - ansible_facts['distribution'] | lower in ["centos", "sangoma", "oracle"]

- name: "Install Statistics Storage for Debian"
  include: debian.yml
  when:
    - ansible_facts['distribution'] | lower in ["debian", "ubuntu"]
    - ansible_facts['distribution_major_version'] | int >= 10
