- name: "Install Storage for CentOS"
  ansible.builtin.include_tasks: centos.yml
  when:
    - ansible_facts['distribution'] | lower in ["centos", "sangoma", "oracle", "rocky"]

- name: "Install Storage for Debian"
  ansible.builtin.include_tasks: debian.yml
  when:
    (ansible_facts['distribution'] | lower == "debian" and
      ansible_facts['distribution_major_version'] | int >= 10) or
    (ansible_facts['distribution'] | lower == "ubuntu" and
      ansible_facts['distribution_version'] in ["20.04"])

- name: "Configure MongoDB and collections"
  ansible.builtin.include_tasks: configure.yml
