- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for Grafana repository"
          apt_key:
            url: "https://packages.grafana.com/gpg.key"
            state: present

        - name: "Add Grafana repository"
          apt_repository:
            repo: deb https://packages.grafana.com/oss/deb stable main
            state: present
            filename: grafana

    - name: "Install Grafana"
      apt:
        pkg:
          - grafana
        update_cache: yes
      notify:
        - restart grafana-server
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop Grafana"
      systemd:
        name: grafana-server
        enabled: no
        state: stopped

    - name: "Uninstall Grafana"
      apt:
        pkg:
          - grafana
        autoremove: yes
        state: absent

    - name: "Purge project files"
      block:
        - name: "Checking project files"
          stat:
            path: "{{item}}"
          register: folder_stats
          with_items:
            - "/etc/grafana/provisioning/datasources/sip3-datasource.yml"
            - "/etc/grafana/provisioning/dashboards/sip3-technical_dashboard.json"
            - "/etc/grafana/provisioning/dashboards/sip3-sip_metrics.json"
            - "/etc/grafana/provisioning/dashboards/sip3-dashboard.yml"
            - "/etc/yum.repos.d/grafana.repo"
        - name: "Delete project files"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == false
          with_items:
            - "{{folder_stats.results}}"
        - name: "Delete project folders"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == true
          with_items:
            - "{{folder_stats.results}}"
      ignore_errors: yes
  when: state == "absent"
