- name: "Install Grafana for CentOS"
  include: centos.yml
  when:
    - ansible_facts['distribution'] | lower in ["centos", "sangoma", "oracle"]

- name: "Install Grafana for Debian"
  include: debian.yml
  when:
    - ansible_facts['distribution'] | lower in ["debian", "ubuntu"]
    - ansible_facts['distribution_major_version'] | int >= 10

- name: "Configure Grafana"
  include: configure.yml
