- name: Copy sip3-salto configuration (application.yml)
  template:
    src: templates/application.yml.j2
    dest: "{{root}}/opt/sip3/salto.yml"
    mode: 0777
  when: state == 'started'

- name: Copy sip3-salto configuration (logback.xml)
  template:
    src: templates/logback.xml.j2
    dest: "{{root}}/opt/sip3/salto.xml"
    mode: 0777
  when: state == 'started'

- name: Copy sip3-salto configuration (sip_message_udf.groovy)
  template:
    src: templates/udf/sip_message_udf.groovy.j2
    dest: "{{root}}/opt/sip3/udf/sip_message_udf.groovy"
    mode: 0777
  when: state == 'started'

- name: Install/Uninstall 'sip/sip3-salto:{{version}}' container
  docker_container:
    name: sip3-salto
    image: "sip3/sip3-salto:{{version}}"
    networks:
      - name: sip3
        aliases:
          - sip3-salto
    ports:
      - 15060:15060/udp
      - 15090:15090/udp
    volumes:
      - "{{root}}/log/sip3:/var/log/sip3-salto"
      - "{{root}}/opt/sip3:/opt/sip3"
    env:
      JAVA_OPTS: "-Xms128m -Xmx256m"
      CONFIG_FILE: "/opt/sip3/salto.yml"
      LOGBACK_FILE: "/opt/sip3/salto.xml"
      UDF_FOLDER: "/opt/sip3/udf"
    restart: yes
    state: "{{state}}"