- name: restart sip3-captain
  systemd:
    name: sip3-captain
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart sip3-captain@
  systemd:
    name: sip3-captain@{{ captain.pcap.dev }}
    daemon_reload: true
    state: restarted
    enabled: true
