- name: "Installing"
  block:
    - name: "Disable SELinux"
      selinux:
        state: disabled

    - name: "Install packages"
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - libpcap
          - java-11-openjdk
          - sip3-captain-{{ edition }}

    - name: "Set Java home"
      set_fact:
        java:
          home: "/usr/lib/jvm/jre-11"
  when: state == "started"

- name: "Uninstalling"
  block:

    - name: "Stop SIP3 Captain"
      systemd:
        name: sip3-captain
        enabled: no
        state: stopped
      when:
        - captain.pcap.dev is not defined

    - name: "Stop SIP3 Captain interface capture"
      systemd:
        name: "sip3-captain-interface@{{ captain.pcap.dev }}"
        enabled: no
        state: stopped
      when:
        - captain.pcap.dev is defined

    - name: "Uninstall package"
      yum:
        name: sip3-captain-{{ edition }}
        state: absent
  when: state == "absent"
