- name: "Installing"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: "Add SIP3 repository"
      yum_repository:
        name: sip3
        description: "SIP3 repository"
        baseurl: https://repo.sip3.io/yum/{{ edition }}/
        gpgkey: https://repo.sip3.io/yum/keyFile
        gpgcheck: yes
        proxy: "{{ proxy | default('_none_') }}"

    - name: "Install packages"
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - libpcap
          - java-11-openjdk
          - sip3-captain-{{ edition }}

    - name: "Set Java home"
      set_fact:
        java:
          home: "/usr/lib/jvm/jre-11"
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop SIP3 Captain"
      systemd:
        name: sip3-captain
        enabled: no
        state: stopped

    - name: "Uninstall package"
      yum:
        name: sip3-captain-{{ edition }}
        state: absent
  when: state == "absent"
