- name: "Create SIP3 Captain basic configuration files"
  template:
    src: "{{ item.name }}.j2"
    dest: "/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "sip3"
    group: "sip3"
  loop:
    - { name: "etc/sip3-captain/environment.conf", mode: "0644" }
    - { name: "etc/sip3-captain/vertx-options.json", mode: "0644" }

- name: "Create SIP3 Captain interface configuration files"
  template:
    src: "{{ item.name }}.j2"
    dest: "/{{ item.name.split('.')[0] }}-{{ captain.pcap.dev }}.{{ item.name.split('.')[1] }}"
    mode: "{{ item.mode }}"
    owner: "sip3"
    group: "sip3"
  loop:
    - { name: "etc/sip3-captain/application.yml", mode: "0644" }
    - { name: "etc/sip3-captain/logback.xml", mode: "0644" }
  when: captain.pcap.dev is defined

- name: "Create SIP3 Captain configuration files"
  template:
    src: "{{ item.name }}.j2"
    dest: "/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "sip3"
    group: "sip3"
  loop:
    - { name: "etc/sip3-captain/application.yml", mode: "0644" }
    - { name: "etc/sip3-captain/logback.xml", mode: "0644" }
  when: captain.pcap.dev is not defined

- name: "Restart SIP3 Captain interface capture"
  systemd:
    name: "sip3-captain-interface@{{ captain.pcap.dev }}"
    daemon_reload: true
    state: restarted
    enabled: true
  when:
    - captain.pcap.dev is defined
    - state == "started"

- name: "Restart SIP3 Captain"
  systemd:
    name: sip3-captain
    daemon_reload: true
    state: restarted
    enabled: true
  when:
    - captain.pcap.dev is not defined
    - state == "started"



