- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            name: gnupg
            update_cache: yes

        - name: "Add signing key for SIP3 repository"
          apt_key:
            url: "https://repo.sip3.io/apt/keyFile"
            state: present

        - name: "Add SIP3 repository"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/ {{ edition }} contrib
            state: present

    - name: "Install packages"
      apt:
        pkg:
          - libpcap0.8
          - openjdk-11-jre
          - sip3-captain-{{ edition }}
        update_cache: yes
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop SIP3 Captain"
      systemd:
        name: sip3-captain
        enabled: no
        state: stopped

    - name: "Uninstall package"
      apt:
        name: sip3-captain-{{ edition }}
        state: absent
  when: state == "absent"
