- name: "Installing"
  when: state == "started"
  block:
    - name: "Install gnupg packages"
      apt:
        name: gnupg
        update_cache: yes

    - name: "Add signing key for SIP3 repository"
      apt_key:
        url: "https://repo.sip3.io/apt/keyFile"
        state: present

    - name: "Add SIP3 ce repositores"
      when: edition == "ce"
      block:

        - name: "add SIP3 repo"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/ ce contrib
            state: present

        - name: "add SIP3 Java repo"
          apt_repository:
            repo: deb https://repo.sip3.io/apt/java/ all contrib
            state: present

    - name: "Add SIP3 licensed repository"
      when: edition != "ce"
      block:

        - name: "Create license files directory"
          ansible.builtin.file:
            path: /etc/ssl/repo.sip3.io
            state: directory
            mode: '0755'

        - name: "Copy license files"
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "/{{ item }}"
          with_items:
            - "etc/ssl/repo.sip3.io/{{ license.cert }}"
            - "etc/ssl/repo.sip3.io/{{ license.key }}"

        - name: "Create SIP3 repo apt configuration files"
          template:
            src: "{{ item }}.j2"
            dest: "/{{ item }}"
          with_items:
            - "etc/apt/apt.conf.d/45sip3-io"

        - name: "Add SIP3 ee repository"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/{% if edition != "ee" %}private/{{ edition }}{% endif %} {{ edition }} contrib
            state: present

        - name: "add SIP3 repo"
          apt_repository:
            repo: deb https://repo.sip3.io/apt/java/ all contrib
            state: present
