- name: "Installing"
  block:
    - name: "Install gnupg packages"
      apt:
        name: gnupg
        update_cache: yes

    - name: "Add signing key for SIP3 repository"
      apt_key:
        url: "https://repo.sip3.io/apt/keyFile"
        state: present

    - name: "Add SIP3 ce repository"
      apt_repository:
        repo: deb [ arch=all ] https://repo.sip3.io/apt/ ce contrib
        state: present
      when: edition == "ce"

    - name: "Add SIP3 licensed repository"
      block:
        - name: "Copy license files"
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "/etc/ssl/repo.sip3.io/"
          with_items:
            - "{{ license.cert }}"
            - "{{ license.key }}"

        - name: "Create SIP3 repo apt configuration files"
          template:
            src: "45sip3-io.j2"
            dest: "/etc/apt/apt.conf.d/45sip3-io"

        - name: "Add SIP3 ee repository"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/{% if edition != "ee" %}private/{{ edition }}{% endif %} {{ edition }} contrib
            state: present

      when: edition != "ce"

  when: state == "started"
