- name: "Installing"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: "Install packages"
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - java-11-openjdk
          - sip3-twig-{{ edition }}

    - name: "Set Java home"
      set_fact:
        java:
          home: "/usr/lib/jvm/jre-11"
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop SIP3 Twig"
      systemd:
        name: sip3-twig
        enabled: no
        state: stopped

    - name: "Uninstall package"
      yum:
        name: sip3-twig-{{ edition }}
        state: absent
  when: state == "absent"
