- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for SIP3 repository"
          apt_key:
            url: "https://repo.sip3.io/apt/keyFile"
            state: present

        - name: "Add SIP3 repository"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/ {{ edition }} contrib
            state: present

    - name: "Install packages"
      apt:
        pkg:
           - openjdk-11-jre
           - sip3-twig-{{ edition }}
        update_cache: yes

    - name: "Set Java home"
      set_fact:
        java:
          home: "/usr/lib/jvm/java-11-openjdk-amd64"
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop SIP3 Twig"
      systemd:
        name: sip3-twig
        enabled: no
        state: stopped

    - name: "Uninstall package"
      apt:
        name: sip3-twig-{{ edition }}
        state: absent
  when: state == "absent"
