- name: Create/Delete freeSWITCH directory {{root}}/etc/freeswitch
  file:
    path: "{{root}}/opt/freeswitch"
    mode: 0777
    state: "directory"

- name: Install/Uninstall 'safarov/freeswitch:{{fs_version}}' container
  docker_container:
    name: freeswitch
    image: "safarov/freeswitch:{{fs_version}}"
    network_mode: "bridge"
    ports:
#      - 5060/tcp
#      - 5060/udp
#      - 5061/tcp
#      - 5061/udp
#      - 5070/tcp
#      - 5070/udp
#      - 5080-5081/tcp
#      - 5080-5081/udp
#      - 7443/tcp
#      - 8021/tcp
#      - 16384-32768/udp
#      - 64535-65535/udp
    volumes:
      - "{{root}}/opt/freeswitch:/etc/freeswitch"
    restart: yes
    state: "{{state}}"
