- name: Create/Delete FreeSWITCH directory {{root}}/etc/freeswitch
  file:
    path: "{{root}}/opt/freeswitch"
    mode: 0777
    state: "directory"

- name: Install/Uninstall 'safarov/freeswitch:{{fs_version}}' container
  docker_container:
    name: freeswitch
    image: "safarov/freeswitch:{{fs_version}}"
    network_mode: "host"
    volumes:
      - "{{root}}/opt/freeswitch:/etc/freeswitch"
    restart: yes
    state: "{{state}}"
