- name: "Installing"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: "Add NGINX repository"
      yum_repository:
        name: nginx
        description: NGINX Repository
        baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: no
        proxy: "{{ proxy | default('_none_') }}"

    - name: "Add SIP3 repository"
      yum_repository:
        name: sip3
        description: "SIP3 repository"
        baseurl: https://repo.sip3.io/yum/{{ edition }}/
        gpgkey: https://repo.sip3.io/yum/keyFile
        gpgcheck: yes
        proxy: "{{ proxy | default('_none_') }}"

    - name: "Check and install tar, unzip and NGINX"
      yum:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
          - tar
          - unzip
          - sip3-hoof-{{ edition }}
          - nginx
      notify:
        - restart nginx
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop NGINX"
      systemd:
        name: nginx
        state: stopped
        enabled: no

    - name: "Uninstall NGINX"
      yum:
        name: "{{ packages }}"
        autoremove: yes
        state: absent
      vars:
        packages:
          - sip3-hoof-{{ edition }}
          - nginx
  when: state == "absent"
