- name: "Installing"
  block:
    - name: Disable SELinux
      selinux:
        state: disabled

    - name: "Add NGINX repository"
      yum_repository:
        name: nginx
        description: NGINX Repository
        baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: no
        proxy: "{{ proxy | default('_none_') }}"

    - name: "Check and install tar, unzip and NGINX"
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - tar
          - unzip
          - nginx
      notify:
        - restart nginx
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop NGINX"
      systemd:
        name: nginx
        state: stopped
        enabled: no

    - name: "Uninstall NGINX"
      yum:
        name: nginx
        autoremove: yes
        state: absent

    - name: "Purge project files"
      block:
        - name: "Checking project files"
          stat:
            path: "{{item}}"
          register: folder_stats
          with_items:
            - "/etc/yum.repos.d/nginx.repo"
            - "/var/www/sip3-hoof"
        - name: "Delete project files"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == false
          with_items:
            - "{{folder_stats.results}}"
        - name: "Delete project folders"
          file:
            path: "{{ item.item }}"
            force: true
            state: absent
          when: item.stat.exists == true and item.stat.isdir == true
          with_items:
            - "{{folder_stats.results}}"
      ignore_errors: yes
  when: state == "absent"
