- name: "Create SIP3 Hoof configuration files"
  template:
    src: "{{ item.name }}.j2"
    dest: "/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "root"
    group: "root"
  loop:
    - { name: "etc/nginx/nginx.conf", mode: "0644" }
    - { name: "etc/nginx/conf.d/sip3-hoof.conf", mode: "0644" }
  notify:
    - restart nginx
