- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for NGINX repository"
          apt_key:
            url: "https://nginx.org/keys/nginx_signing.key"
            state: present

        - name: "Add NGINX repository"
          apt_repository:
            repo: deb http://nginx.org/packages/{{ ansible_facts['distribution'] | lower }} {{ ansible_facts['lsb']['codename'] }} nginx
            state: present
            filename: nginx

    - name: "Check and install tar, unzip and NGINX"
      apt:
        name: "sip3-hoof-{{ edition }}"
        update_cache: yes
        state: latest

    - name: "Restart NGINX"
      systemd:
        name: nginx
        state: restarted
        enabled: yes

  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop NGINX"
      systemd:
        name: nginx
        enabled: no
        state: stopped

    - name: "Uninstall NGINX"
      apt:
        pkg:
          - nginx
          - sip3-hoof-{{ edition }}
        state: absent
  when: state == "absent"
