- name: "Installing"
  block:
    - name: "Add repositories"
      block:
        - name: "Install gnupg packages"
          apt:
            pkg:
              - gnupg
            update_cache: yes

        - name: "Add signing key for NGINX repository"
          apt_key:
            url: "https://nginx.org/keys/nginx_signing.key"
            state: present

        - name: "Add NGINX repository"
          apt_repository:
            repo: deb http://nginx.org/packages/debian {{ ansible_facts['lsb']['codename'] }} nginx
            state: present
            filename: nginx

        - name: "Add signing key for SIP3 repository"
          apt_key:
            url: "https://repo.sip3.io/apt/keyFile"
            state: present

        - name: "Add SIP3 repository"
          apt_repository:
            repo: deb [ arch=all ] https://repo.sip3.io/apt/ {{ edition }} contrib
            state: present

    - name: "Check and install tar, unzip and NGINX"
      apt:
        pkg:
          - tar
          - unzip
          - nginx
          - sip3-hoof-{{ edition }}
        update_cache: yes
        state: latest
      notify:
        - restart nginx
  when: state == "started"

- name: "Uninstalling"
  block:
    - name: "Stop NGINX"
      systemd:
        name: nginx
        enabled: no
        state: stopped

    - name: "Uninstall NGINX"
      apt:
        pkg:
          - nginx
          - sip3-hoof-{{ edition }}
        state: absent
  when: state == "absent"
